name: Test Suite

on: [pull_request]

jobs:
  test-suite:
    name: Build Containers and Run Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Pull
        run: |
          docker pull mysql:5.6
          docker pull xibosignage/xibo-xmr:latest
          docker pull xibosignage/xibo-cms:develop
          docker pull xibosignage/xibo-cms:cypress
      - name: Build
        run: |
          docker build . -f Dockerfile.ci -t cms-web --build-arg GIT_COMMIT=${GITHUB_SHA}
      - name: Run Code Sniffer
        run: |
          git fetch origin ${GITHUB_BASE_REF}
          git diff origin/${GITHUB_BASE_REF} > diff.txt
          git diff origin/${GITHUB_BASE_REF} --name-only --diff-filter=ACMR -- "*.php" > files.txt
          docker build -f Dockerfile.codesniffer -t phpcs-app .
          docker run --rm --volume "$PWD":/project phpcs-app /code/vendor/bin/phpcs --standard=/code/vendor/xibosignage/support/src/Standards/xibo_ruleset.xml --report=json --report-\\Micheh\\PhpCodeSniffer\\Report\\Gitlab=phpcs-quality-report.json --file-list=files.txt > phpcs.json || true
          docker run --rm --volume "$PWD":/project phpcs-app /code/vendor/bin/diffFilter --phpcs diff.txt phpcs.json
 