name: Comment Triggered Workflow

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  comment_triggered_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check Comment
        id: check_comment
        run: |
          comment_body="${{ github.event.comment.body }}"
          if [[ "$comment_body" =~ ^TEST:\ (.*)$ ]]; then
            specs="${BASH_REMATCH[1]}"
            echo "Specs to test: $specs"
            echo "TEST_SPECS=$specs" >> $GITHUB_ENV
          else
            echo "No specs specified in the comment."
          fi

      - name: Trigger Workflow
        run: |
          if [[ -n "$TEST_SPECS" ]]; then
            echo "The comment matches, triggering the workflow with directories: $TEST_SPECS."
          else
            echo "No directories specified, exiting with an error."
            exit 1
          fi