name: Comment Triggered Workflow

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  comment_triggered_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check Comment
        id: check_comment
        run: |
          comment_body="${{ github.event.comment.body }}"
          if [[ "$comment_body" =~ ^TEST:\ (.*)$ ]]; then
            directories="${BASH_REMATCH[1]}"
            echo "Directories to test: $directories"
            echo "TEST_DIRECTORIES=$directories" >> $GITHUB_ENV
          else
            echo "No directories specified in the comment."
          fi

      - name: Trigger Workflow
        if: env.TEST_DIRECTORIES != ''
        run: echo "The comment matches, triggering  the workflow."